fruits
przytop/goit-team-project-group-3 pull request #8
Opened 2024-04-07 18:18 UTC by Spudowski

czeka na fotki jeszcze

2024-04-07 19:09 UTC, przytop requested changes
selektorem powinieneś się odwoływać po nazwie klasy a nie po nazwie tagu
i nie powinieneś bez potrzeby pisać takich łańcuchów selektorów
no ale w tym stanie tylko linijka 1 w css stanowi problem

2024-04-07 19:11 UTC, przytop requested changes
id musi być w buttonie

2024-04-08 18:32 UTC, kolegamarceli approved these changes
ok

2024-04-10 21:26 UTC, przytop requested changes
zalecają dawać ścieżkę dostępu na zasadzie
./ dla html
../ dla scss
ale jestem ciekaw czy zadziała tak jak ty masz
letter-spacing daj tu zmienne
font-size 14 jest dodana jako globalna
color background-color tam gdzie możesz dodaj zmienną

2024-04-11 17:49 UTC, przytop approved these changes
poszło

2024-04-11 17:49 UTC, merged